hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "9b4aa67b718ab276c9017d9f9003a0ff46c27d5de6705b4e694f292790c9d663"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "28f680af065a9f5417ebec46917532c86aacf5866e27647a62b448c03af7b01d"

[[files]]
file = "config/yosbr/config/audioplayer/audioplayer-server.properties"
hash = "1e611c9173c793c6434b998bcaaf40b0f3a0131ab3619292c1a4384594db4121"

[[files]]
file = "config/yosbr/config/entity_model_features.json"
hash = "fbb9a47d877b3b9638c3c57bd53cde5292811a513083ea58c81c1a971a700b3a"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "1bfc640ac9a5347f2cc06edb01f10cb750fd7073d9809ab66f121ab2e0b9b35e"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "2b9348b31a8a0d8239c5a3bf9cc3afb7b6d2a7b1bc14cd3558bb2c6c72bc7028"

[[files]]
file = "config/yosbr/config/voicechat/translations.properties"
hash = "b8215b84232be41438ffb7c7304b57b0677c9cad49b717db59900872080adf20"

[[files]]
file = "config/yosbr/config/voicechat/username-cache.json"
hash = "080e092a2cdf65562653c853debb74b8a052c9423a12598eada8076de8ef9648"

[[files]]
file = "config/yosbr/config/voicechat/voicechat-client.properties"
hash = "90fe49918c922fc32f98ccf770ca16651da6d2c02d042578e708397c5be15ba5"

[[files]]
file = "config/yosbr/config/voicechat/voicechat-server.properties"
hash = "7d49f4a92ed5c5490880869e52a58d291f787f42d93923697aa388830cab3e62"

[[files]]
file = "config/yosbr/config/voicechat/voicechat-volumes.properties"
hash = "58242ef3075b166845e0081281b01113a55b9d095104a68b167e7b4bc08b87c5"

[[files]]
file = "config/yosbr/options.txt"
hash = "71d2af7a522638c6e6f7253966e2f8d6bc796c0c0c4b936f8e2e4455221e125f"

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "e0977ddb68d1052103b190855db0f56a85499351fcd1f43df42c4ff37021b01c"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "fcea55e0347a1281308c6f57d7a6c2587d31f716dc4f72d876e4aec09902def6"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "17e7de63579b066cea4b6db60318617956c1925891edc562085cd72544a763b9"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "5ab81359d4654812c2f4dd40f6db5bb51e217a228827d5cc351a40611f05d7de"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "9854603f767980c514aefe9c391a6d3fa89dc6be18d23ab462f2a3bbabe7652c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "982801b4473e11e6f8c5899f18a260515239dfce397c650c6920fc6ae03f6abb"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a89555e4ccf7ba3541cae70de8e1c11b007a50993f3b7ffc490932029ed8fdf5"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a2991786a3523846ee1dcaa4c34c9f1d7a544ea4dbf252df8482b19549009b4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "15bce919514325447e487d260ec4458165fb4537ccadb9a0e740df4bcf3cb0ef"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "9711d569e7594f7ed586d53523ccc262e56fddac13484dd5a5f245e7ae239eb7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7f26c8df78d02b1d63a723a3a45b838415126da5296ac67b0414e564da30a421"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "c2cd3b91119eb55ab7ece9fdefa69f39d435667390575dcda4b67dddad7874e9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "0544fefc6f04f2b408b2c6b4dd3e4bf7d0a4048f1fad6ddf63357549d7446165"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4c4f8569adba682de05800e73690fec8ce64d9d86341862ac6d9315d9dec01eb"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "f8231b6ff29c1ff27d5acd191929609e98706c498abe61369db53554b0638548"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "a625f1f205b6d9152a66724dfc8ebe2952705daf0884e10be16c288c847346fc"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "13369d7a10a47895f33629f000945d6bdf43f7b19a9ff1ca2ecfbc209c1ac431"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "383d8df46529ce54b4b0574be2fd9eba4f45d8c85aa668604e152fca3e439f5a"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "4a0890e5d860b2c51106274bd9573c6968c0add25712ed14572226337e2c9145"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "11db2f1acc702cfc92d43efd8800b4b9db54e3c059ec1d35754618adacffc334"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0cbc900ae05bdd88801539eeee6b95dde99426f1d5c2c7c8c194e5f78bbd6e52"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4e4627ce19e119721a27a2ef00769d3a744f36db67d11ad3959d785462aefe1f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b01870e848aee7e1a2e19c6530bdd4c479b21a2f6f67134da75210844252d48f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "cf2a50560f03613b7356103544a1f11d38da73fc445b5ec0b5a29c10543c3cfd"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d44e2b5db1fb0c90d9ec5f25a153a437ea71c59a499491b6d639fff69cec8ba4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "resourcepacks/Redstone Tweaks 2.5.3.zip.rpo"
hash = "5c353417428ccd7e9182d2a4ff226640dcea2af2d90b9a0876219545be60577c"

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "64f90fd9619a092a8a5493d6ad9605bc5fec13f50f02feef1dcf47c9496a80bd"
metafile = true

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "31b53c71c2bf08da156167befe54b5717e71ee871e10ef78a70967a0bdc8b56b"
metafile = true
