name = "CoreOptimized"
author = "SniperXJohn"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa31cb6b8fdabab111782f86028520c9464f1c22cec50743601d0fc51f96fbea"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
