name = "CoreOptimized"
author = "SniperXJohn"
version = "1.8.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "971b05b307b070532cc9c1d06b17c931fa586b876abe595fcf2d690305fc37c0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
