name = "CoreOptimized"
author = "SniperXJohn"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c949c7db5227b3e33035ad56a2d4f6e323025dd6ba27afe444917abc63198e3e"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
