name = "CoreOptimized"
author = "SniperXJohn"
version = "1.7.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6bd0eb238e94363d1e1098142804e48acde6e51258a39978f6c06ddc9dd926b"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
