name = "CoreOptimized"
author = "SniperXJohn"
version = "1.7.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d631ed88af8d1a03d061cc50b073f0621cff3bd8129416d91acb14346e18a1c5"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
