name = "CoreOptimized"
author = "SniperXJohn"
version = "1.7.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afdbd325ce106797b6dd0785f4eb22ff4bf4f8ae05b4509c1678ca956ce790f4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
