name = "CoreOptimized"
author = "SniperXJohn"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0f89893103e2b9acf45ae0497e6c965f3c2ba9143843aad16b11c5d39fe7f9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
